# Generated by Django 5.2.12 on 2026-04-22 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_books_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'ordering': ['-created_time'], 'permissions': [('can_publish', 'Can Publish Books')]},
        ),
    ]
