# Generated by Django 5.2.12 on 2026-04-27 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
