# Generated by Django 5.2.12 on 2026-05-15 14:33

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_verificationcode_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationcode',
            name='code',
            field=models.PositiveIntegerField(default=accounts.models.generate_code),
        ),
    ]
