# Generated by Django 5.2.12 on 2026-04-24 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='document',
            table='documents',
        ),
    ]
